name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v2

    - name: setup 
      run: |
        luarocks install luacheck
        
    - name: ROBLOX luacheck
      uses: rwilliaise/roblox-luacheck@f11b62d0e688989e2c39cb114d98d3b9ac9324da
